version: 2

sources:
  - name: dbt_ippon_training
    database: DB_DBT_LCAVAREE_DEV
    schema: SOURCE
    tables:
      - name: RESTAURANTS
        description: This table contains informations related to the restaurants
      - name: ORDERS
        description: This table contains informations related to the orders
        columns:
          - name: turnover