version: 2

sources:
  - name: sources 
    database : jnadal_db
    schema: source
    tables:
      - name: orders
        description : Raw orders data
        columns:
          - name: identifier
            description: Primary key for orders
            tests:
              - unique
              - not_null
          - name: payment_method
            description: "{{doc('order_payment')}}"
            tests:
              - accepted_values:
                  values:
                    - card
                    - cash
                    - cheque
                    - meal_ticket
      - name: restaurants
        description: Raw restaurants data
        columns:
          - name: identifier
            description: Primary key for restaurants
            tests:
              - unique
              - not_null
      - name: dishes
        description: Raw dishes data
        columns:
          - name: identifier
            description: Primary key for dishes
            tests:
              - unique
              - not_null
      - name: fuzzy_orders